services:
  db:
    container_name: nextjs-dashboard-postgres
    image: postgres:17.7
    restart: unless-stopped
    command: postgres -c "listen_addresses=*"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - 5400:5432

